### ISSUE TITLE
On Ubuntu 16: /usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#14]
I run:
apt install npm  
git clone https://github.com/animetosho/Nyuu.git  
cd Nyuu
npm install --no-optional --production
ln -s "`pwd`/bin/nyuu.js" /usr/bin/nyuu
chmod a+x bin/nyuu.js
nyuu
/usr/bin/env: ‘node’: No such file or directory

Fixed by:

`ln -s /usr/bin/nodejs /usr/bin/node`

:)

**Comment by animetosho** [comment]
> Fixed by: `ln -s /usr/bin/nodejs /usr/bin/node`

The more Debian/Ubuntu way to do it is `apt-get install nodejs-legacy`, though it ultimately does the same thing.

Alternatively, you can edit the first line of the bin/nyuu.js file to use `nodejs` instead of `node`. :)

**Comment by scriptzteam** [comment]
Thx :)

**Comment by iwhyer** [comment]
@animetosho Thanks :)

**Comment by Maximumz** [comment]
Thanks @animetosho

**Comment by cryptogab** [comment]
@animetosho  Still up-to-date thank you

**Comment by Ash-Radwan** [comment]
@animetosho Still rolling thanks !

**Comment by arlCode** [comment]
Worked for me, thanks!

**Comment by MalloZup** [comment]
btw shouldn't be nodejs-legacy the default one? to me look like a bug on debian. I had same issue on ubuntu 17.04

I vote for a bug on packaging debian

**Comment by animetosho** [comment]
My guess is that they don't want to pollute the `node` name, possibly because another application uses it. NodeJS wants their binary to be called "node", but Debian wants it to be called "nodejs".

I probably wouldn't consider it a bug, in fact, I'd blame NodeJS for going for such a generic name.

**Comment by marciotognere** [comment]
thanks

**Comment by SolArt7** [comment]
Thanks!

**Comment by Bidon15** [comment]
Thanks so much!

**Comment by RezaNurRochmat13** [comment]
Thanks its working :)

**Comment by amirgee** [comment]
Thanks Thanks Thanks :-*

**Comment by phsantosjr** [comment]
Thanks

**Comment by abhishek321** [comment]
Thanks

**Comment by M-Devloo** [comment]
Still works as a charm! Thanks

**Comment by djgio02** [comment]
Thanks

**Comment by bryantnate** [comment]
> > Fixed by: `ln -s /usr/bin/nodejs /usr/bin/node`
> 
> The more Debian/Ubuntu way to do it is `apt-get install nodejs-legacy`, though it ultimately does the same thing.
> 
> Alternatively, you can edit the first line of the bin/nyuu.js file to use `nodejs` instead of `node`. :)

Please help on how to roll back this action... I tried it, and it just messed node up.

`/usr/local/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by bryantnate** [comment]
> > Fixed by: `ln -s /usr/bin/nodejs /usr/bin/node`
> 
> The more Debian/Ubuntu way to do it is `apt-get install nodejs-legacy`, though it ultimately does the same thing.
> 
> Alternatively, you can edit the first line of the bin/nyuu.js file to use `nodejs` instead of `node`. :)

I tried this option and it seems things are just messed up a lot more.
```/usr/local/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3```

**Comment by CallMeKanG** [comment]
> > > Fixed by: `ln -s /usr/bin/nodejs /usr/bin/node`
> > 
> > 
> > The more Debian/Ubuntu way to do it is `apt-get install nodejs-legacy`, though it ultimately does the same thing.
> > Alternatively, you can edit the first line of the bin/nyuu.js file to use `nodejs` instead of `node`. :)
> 
> I tried this option and it seems things are just messed up a lot more.
> 
> ```
>       let notifier = require('update-notifier')({pkg})
>       ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3```
> ```

https://stackoverflow.com/questions/50316693/npm-update-broke-npm this solution fixed my problem

**Comment by tamil07** [comment]
Getting the below error, post fixing the nodejs issue.

root@ubuntu1604:~/hygieia/UI# gulp serve
[10:48:36] Using gulpfile ~/hygieia/UI/gulpfile.js
[10:48:36] Starting 'build'...
[10:48:36] Starting 'clean'...
[10:48:36] Finished 'clean' after 60 ms
[10:48:36] Starting 'assets'...
[10:48:36] Starting 'themes'...
[10:48:36] Starting 'fonts'...
[10:48:36] Starting 'js'...
[10:48:36] Starting 'views'...
[10:48:36] Starting 'test-data'...
[10:48:46] Finished 'themes' after 9.68 s
[10:48:46] Finished 'assets' after 9.69 s
[10:48:46] Finished 'test-data' after 9.74 s
[10:48:46] Finished 'views' after 9.92 s
[10:48:47] Finished 'js' after 10 s
[10:48:52] Finished 'fonts' after 15 s
[10:48:52] Starting 'html'...
[10:48:52] gulp-inject 29 files into index.html.
[10:48:52] gulp-inject 171 files into index.html.
[10:48:52] Finished 'html' after 192 ms
[10:48:52] Finished 'build' after 16 s
[10:48:52] Starting 'serve'...
[10:48:52] 'serve' errored after 6.4 ms
[10:48:52] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/hygieia/UI/node_modules/localtunnel/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
