### ISSUE TITLE
Versions 0.3.3 and 0.3.4 fail on previously working command line

### ISSUE THREAD

**Issue by scytalezero** [animetosho/Nyuu#23]
The following command line works fine on 0.3.2:

nyuu.exe --host secure.news.us.easynews.com --port 443 --ssl true --ignore-cert true --user user --password password --connections 20 --from somebody --groups alt.binaries.backup --check-connections 2 --check-tries 3 --check-delay 5s --check-retry-delay 30s --check-post-tries 1 --meta password=password --meta category= --out C:\temp\test.nzb --nzb-compress gzip --progress log:1s --subdirs keep --overwrite C:\Users\bcreel\AppData\Local\Temp\cj4stjxch0000lkcic3ijoa2d

However, on 0.3.3 and 0.3.4 it throws the following error:

..........\node_modules\nyuu\bin\nyuu.js:811
                                progress.push({type: 'log', interval: parseTime(arg) || 60});
                                                                      ^

ReferenceError: parseTime is not defined
    at C:\Users\bcreel\AppData\Roaming\npm\node_modules\dark-archive\node_modules\nyuu\bin\nyuu.js:811:43
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\bcreel\AppData\Roaming\npm\node_modules\dark-archive\node_modules\nyuu\bin\nyuu.js:804:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)

**Comment by animetosho** [comment]
Urgh, sorry for breaking the `--progress log` option, and thanks for pointing that out.

**Comment by scytalezero** [comment]
Thanks for the quick response!
