### ISSUE TITLE
fileuploader.js - Unexpected token when executing nyuu

### ISSUE THREAD

**Issue by tihsamikah** [animetosho/Nyuu#24]
Good Morning,

Today I updated my server (Arch Linux), and noticed nyuu no longer worked.

I completely removed nyuu using the suggested uninstall method, and reinstalled nyuu, with no luck.

I then decided to completely remove node.js and npm ( and its dependencies) and reinstall them all.

Now when I execute nyuu I get the following error message - 

```
[tihsamikah@mrlaptop ~]$ nyuu
/usr/lib/node_modules/nyuu/lib/fileuploader.js:186
                                        par = ParPar.PAR2Gen(, {sliceSiz}, {opts});
                                                             ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/nyuu/bin/nyuu.js:941:71)
[tihsamikah@mrlaptop ~]$ 

```
I've installed a fresh copy of manjaro (sorry - pacman based too) and Ubuntu server, and still the same result.

let me know what additional information you need, and I'll assist as best I can :)

**Comment by animetosho** [comment]
Looks like the wrong thing got published to NPM, sorry about that.

Can you please retry now?

**Comment by tihsamikah** [comment]
mate - that did the trick all fixed :)

thanks for the prompt help - and keep up the great work :)
