### ISSUE TITLE
Problem with fs.js

### ISSUE THREAD

**Issue by sailorpsy** [animetosho/Nyuu#30]
I've been using the v0.3.2 release on Windows. I'm trying to upgrade to v0.3.4, but I get an error. (v0.3.3 also has the error.)

```
fs.js:540
  binding.open(pathModule._makeLong(path),
          ^

TypeError: flags must be an int
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at WriteStream.open (fs.js:1834:6)
    at new WriteStream (fs.js:1824:10)
    at Object.fs.createWriteStream (fs.js:1780:10)
    at Object.UploadManager (nexe.js:5402:45)
    at Immediate.<anonymous> (nexe.js:3008:12)
    at Immediate.immediate._onImmediate (timers.js:448:18)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

Here's my command line.
```
nyuu.exe
-C
config.json
--from
<removed>
--groups
<removed>
--subject
<removed>
--progress
stderr
--progress
http:localhost:8888
-o
<removed>.nzb
-O
<folder removed>
```

`config.json`:
```
{
	"host":               <removed>,
	"port":               563,
	"ssl":                true,
	"ignore-cert":        false,
	"user":               <removed>,
	"password":           <removed>,
	"connections":        15,
	
	"connect-retries":    3,
	
	"article-size":       "768000",
	
	"check-host":               <removed>,
	"check-port":               563,
	"check-ssl":                true,
	"check-ignore-cert":        false,
	"check-user":               <removed>,
	"check-password":           <removed>,
	
	"check-connections":  10,
	"check-tries":        6,
	"check-delay":        "15s",
	"check-retry-delay":  "15s",
	"check-post-tries":   10,
	
	"skip-errors":        false,
	
	"out":                null,
	"overwrite":          false,
	
	"quiet":              false,
	
	"subdirs":            "keep"
}

```

**Comment by animetosho** [comment]
Thanks for reporting!

I should probably make a new release, as I've actually fixed this bug in the latest code (but there isn't a Windows EXE build). If you're wondering, the overwrite parameter (`-O`) is handled incorrectly in v0.3.4, which causes the crash.

**Comment by sailorpsy** [comment]
OK, great!

I've been thinking about removing `-O` anyway, so I will to get v0.3.4 working. Thanks.

**Comment by animetosho** [comment]
v0.3.6 now released, which should include a fix for this.
