### ISSUE TITLE
I am getting a few errors while Building Binary

### ISSUE THREAD

**Issue by uttham29** [animetosho/Nyuu#70]
fs.js:114
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at copyCC (/root/Nyuu-0.3.8/nexe/build.js:230:16)
    at Object.<anonymous> (/root/Nyuu-0.3.8/nexe/build.js:246:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

My folders are like this
https://ibb.co/Wz1bVwB

and build.js
https://ibb.co/0BSyGjb

**Comment by BlepingMatrix** [comment]
Don't build as root. It always gives errors.

**Comment by uttham29** [comment]
successfully built nyuu .but when i execute it is giving me these following errors
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/home/uttham/Nyuu-0.3.8/nexe/bulid.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by BlepingMatrix** [comment]
Why aren't you using NPM to install it? It takes care of all dependencies.

try `npm install -g nyuu`

**Comment by animetosho** [comment]
The build script hasn't been updated to deal with yencode v1.1.0 - try v1.0.8 instead. *yencode.cc* should be a file, not a directory.

The build script is somewhat fragile, so I wouldn't be surprised if you get more issues - I can try to help, but just letting you know what you're getting yourself into.
